import React from 'react';
import { Sparkles } from 'lucide-react';

interface AiBadgeProps {
  /** Optional label override; defaults to "AI". */
  label?: string;
  className?: string;
}

/**
 * Small, consistent marker shown wherever content is machine-generated
 * (suggestions, AI-proposed titles/tags, summaries). Implements G5.5:
 * AI output must be clearly distinguishable from the user's own or source content.
 */
export const AiBadge = ({ label = 'AI', className = '' }: AiBadgeProps) => (
  <span
    className={`inline-flex items-center gap-1 rounded-full bg-primary/10 text-primary px-2 py-0.5 text-[10px] font-medium font-josefin leading-none ${className}`}
    title="This content was generated by AI"
    aria-label="AI generated"
  >
    <Sparkles className="h-2.5 w-2.5" />
    {label}
  </span>
);
